/* Function generated by Maple to Scilab interface */

# include  "../routines/machine.h" 
# include <math.h>

void fooc5(arg_k, x,fmat)
double *arg_k, x[3],fmat[2][2];
  {
  double t3;
  double k=*arg_k;
  t3 = sin(x[2]);
  fmat[0][0] = k*x[0];
  fmat[0][1] = (1-k)*t3;
  fmat[1][0] = x[1]-x[0];
  fmat[1][1] = x[2];
  }
