/* Function generated by Maple to Scilab interface */

# include  "../routines/machine.h" 
# include <math.h>

void fooc4(arg_x,arg_y,fmat)
double *arg_x,*arg_y,fmat[2][1];
  {
  
  double x=*arg_x;
  double y=*arg_y;
  fmat[0][0] = x;
  fmat[1][0] = y;
  }
