/* Function generated by Maple to Scilab interface */

# include  "../routines/machine.h" 
# include <math.h>

void fooc3(arg_x,fmat)
double *arg_x,fmat[1][2];
  {
  double t1,t2,t4;
  double x=*arg_x;
  t1 = sqrt(x);
  t2 = x*x;
  t4 = sin(-1+t2);
  fmat[0][0] = t1;
  fmat[0][1] = -t4;
  }
