/* Function generated by Maple to Scilab interface */

# include  "../routines/machine.h" 
# include <math.h>

void fooc2(fmat)
double fmat[10][5];
  {
  
  fmat[0][0] = -85;
  fmat[0][1] = 57;
  fmat[0][2] = 54;
  fmat[0][3] = 1;
  fmat[0][4] = 94;
  fmat[1][0] = -55;
  fmat[1][1] = -59;
  fmat[1][2] = -5;
  fmat[1][3] = -47;
  fmat[1][4] = 83;
  fmat[2][0] = -37;
  fmat[2][1] = 45;
  fmat[2][2] = 99;
  fmat[2][3] = -91;
  fmat[2][4] = -86;
  fmat[3][0] = -35;
  fmat[3][1] = -8;
  fmat[3][2] = -61;
  fmat[3][3] = -47;
  fmat[3][4] = 23;
  fmat[4][0] = 97;
  fmat[4][1] = -93;
  fmat[4][2] = -50;
  fmat[4][3] = -61;
  fmat[4][4] = -84;
  fmat[5][0] = 50;
  fmat[5][1] = 92;
  fmat[5][2] = -12;
  fmat[5][3] = 41;
  fmat[5][4] = 19;
  fmat[6][0] = 79;
  fmat[6][1] = 43;
  fmat[6][2] = -18;
  fmat[6][3] = -58;
  fmat[6][4] = -50;
  fmat[7][0] = 56;
  fmat[7][1] = -62;
  fmat[7][2] = 31;
  fmat[7][3] = -90;
  fmat[7][4] = 88;
  fmat[8][0] = 49;
  fmat[8][1] = 77;
  fmat[8][2] = -26;
  fmat[8][3] = 53;
  fmat[8][4] = -53;
  fmat[9][0] = 63;
  fmat[9][1] = 66;
  fmat[9][2] = -62;
  fmat[9][3] = -1;
  fmat[9][4] = 85;
  }
