/* Function generated by Maple to Scilab interface */

# include  "../routines/machine.h" 
# include <math.h>

void fooc6(arg_k, x,fmat)
double *arg_k, x[2][3],fmat[2][3];
  {
  
  double k=*arg_k;
  fmat[0][0] = x[0][0]+x[1][1];
  fmat[0][1] = 10*k;
  fmat[0][2] = x[1][2];
  fmat[1][0] = k*(x[0][1]+x[1][0]);
  fmat[1][1] = 1;
  fmat[1][2] = x[0][2];
  }
