/* Function generated by Maple to Scilab interface */

# include  "../routines/machine.h" 
# include <math.h>

void fooc1(arg_x,fmat)
double *arg_x,fmat[1][1];
  {
  double t2,t3;
  double x=*arg_x;
  t2 = exp(1+x);
  t3 = sin(x);
  fmat[0][0] = t2/t3;
  }
