/* Function generated by Maple to Scilab interface */

# include  "../routines/machine.h" 
# include <math.h>

void fooc7(arg_k, x,ij,v,mn)
double *arg_k, x[2][3];
int ij[2][3];
double *v;
int *mn;
  {
  
  double k=*arg_k;
  mn[0] = 20;
  mn[1] = 20;
  ij[0][0] = 15;
  ij[0][1] = 2;
  ij[0][2] = 1;
  ij[1][0] = 6;
  ij[1][1] = 4;
  ij[1][2] = 1;
  v[0] = k*(x[0][1]-x[1][0]);
  v[1] = k*x[1][2];
  v[2] = x[0][0]+x[1][1];
  }
