/* Function generated by Maple to Scilab interface */

# include  "../routines/machine.h" 
# include <math.h>

void fooc8(fmat)
double fmat[10][5];
  {
  
  fmat[0][0] = -88;
  fmat[0][1] = 40;
  fmat[0][2] = -5;
  fmat[0][3] = -7;
  fmat[0][4] = -73;
  fmat[1][0] = -43;
  fmat[1][1] = 61;
  fmat[1][2] = -28;
  fmat[1][3] = 58;
  fmat[1][4] = -91;
  fmat[2][0] = -73;
  fmat[2][1] = 40;
  fmat[2][2] = 4;
  fmat[2][3] = -94;
  fmat[2][4] = 1;
  fmat[3][0] = 25;
  fmat[3][1] = -78;
  fmat[3][2] = -11;
  fmat[3][3] = -68;
  fmat[3][4] = 5;
  fmat[4][0] = 4;
  fmat[4][1] = 62;
  fmat[4][2] = 10;
  fmat[4][3] = 14;
  fmat[4][4] = -86;
  fmat[5][0] = -59;
  fmat[5][1] = 11;
  fmat[5][2] = 57;
  fmat[5][3] = -35;
  fmat[5][4] = 43;
  fmat[6][0] = 62;
  fmat[6][1] = 88;
  fmat[6][2] = -82;
  fmat[6][3] = -14;
  fmat[6][4] = -4;
  fmat[7][0] = -55;
  fmat[7][1] = 1;
  fmat[7][2] = -48;
  fmat[7][3] = -9;
  fmat[7][4] = -50;
  fmat[8][0] = 25;
  fmat[8][1] = 30;
  fmat[8][2] = -11;
  fmat[8][3] = -51;
  fmat[8][4] = 50;
  fmat[9][0] = 9;
  fmat[9][1] = 81;
  fmat[9][2] = 38;
  fmat[9][3] = -73;
  fmat[9][4] = 67;
  }
