c      
c     SUBROUTINE foof6
c      
      subroutine foof6(k,x,fmat)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        doubleprecision k,x(2,3)
        dimension fmat(3,2)
         fmat(1,1) = x(1,1)+x(2,2)
         fmat(1,2) = k*(x(1,2)+x(2,1))
         fmat(2,1) = 10*k
         fmat(2,2) = 1
         fmat(3,1) = x(2,3)
         fmat(3,2) = x(1,3)
      end
