c      
c     SUBROUTINE foof3
c      
      subroutine foof3(x,fmat)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        doubleprecision x
        dimension fmat(2,1)
      t1 = sqrt(x)
      t2 = x**2
      t4 = sin(-1+t2)
         fmat(1,1) = t1
         fmat(2,1) = -t4
      end
