c      
c     SUBROUTINE foof1
c      
      subroutine foof1(x,fmat)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        doubleprecision x
        dimension fmat(1,1)
      t2 = exp(1+x)
      t3 = sin(x)
         fmat(1,1) = t2/t3
      end
