c      
c     SUBROUTINE foof2
c      
      subroutine foof2(fmat)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        dimension fmat(5,10)
         fmat(1,1) = -85
         fmat(1,2) = -55
         fmat(1,3) = -37
         fmat(1,4) = -35
         fmat(1,5) = 97
         fmat(1,6) = 50
         fmat(1,7) = 79
         fmat(1,8) = 56
         fmat(1,9) = 49
         fmat(1,10) = 63
         fmat(2,1) = 57
         fmat(2,2) = -59
         fmat(2,3) = 45
         fmat(2,4) = -8
         fmat(2,5) = -93
         fmat(2,6) = 92
         fmat(2,7) = 43
         fmat(2,8) = -62
         fmat(2,9) = 77
         fmat(2,10) = 66
         fmat(3,1) = 54
         fmat(3,2) = -5
         fmat(3,3) = 99
         fmat(3,4) = -61
         fmat(3,5) = -50
         fmat(3,6) = -12
         fmat(3,7) = -18
         fmat(3,8) = 31
         fmat(3,9) = -26
         fmat(3,10) = -62
         fmat(4,1) = 1
         fmat(4,2) = -47
         fmat(4,3) = -91
         fmat(4,4) = -47
         fmat(4,5) = -61
         fmat(4,6) = 41
         fmat(4,7) = -58
         fmat(4,8) = -90
         fmat(4,9) = 53
         fmat(4,10) = -1
         fmat(5,1) = 94
         fmat(5,2) = 83
         fmat(5,3) = -86
         fmat(5,4) = 23
         fmat(5,5) = -84
         fmat(5,6) = 19
         fmat(5,7) = -50
         fmat(5,8) = 88
         fmat(5,9) = -53
         fmat(5,10) = 85
      end
