c      
c     SUBROUTINE foof5
c      
      subroutine foof5(k,x,fmat)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        doubleprecision k,x(3)
        dimension fmat(2,2)
      t4 = sin(x(3))
         fmat(1,1) = k*x(1)
         fmat(1,2) = x(2)-x(1)
         fmat(2,1) = (1-k)*t4
         fmat(2,2) = x(3)
      end
