c      
c     SUBROUTINE foof8
c      
      subroutine foof8(fmat)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        dimension fmat(5,10)
         fmat(1,1) = 49
         fmat(1,2) = 78
         fmat(1,3) = 17
         fmat(1,4) = 72
         fmat(1,5) = -99
         fmat(1,6) = -85
         fmat(1,7) = -86
         fmat(1,8) = 30
         fmat(1,9) = 80
         fmat(1,10) = 72
         fmat(2,1) = 66
         fmat(2,2) = -29
         fmat(2,3) = -91
         fmat(2,4) = -53
         fmat(2,5) = -19
         fmat(2,6) = -47
         fmat(2,7) = 68
         fmat(2,8) = -72
         fmat(2,9) = -87
         fmat(2,10) = 79
         fmat(3,1) = 43
         fmat(3,2) = -66
         fmat(3,3) = -53
         fmat(3,4) = -61
         fmat(3,5) = -23
         fmat(3,6) = -37
         fmat(3,7) = 31
         fmat(3,8) = -34
         fmat(3,9) = -42
         fmat(3,10) = 88
         fmat(4,1) = -76
         fmat(4,2) = -65
         fmat(4,3) = 25
         fmat(4,4) = 28
         fmat(4,5) = -61
         fmat(4,6) = -60
         fmat(4,7) = 9
         fmat(4,8) = 29
         fmat(4,9) = -66
         fmat(4,10) = -32
         fmat(5,1) = 78
         fmat(5,2) = 39
         fmat(5,3) = 94
         fmat(5,4) = 68
         fmat(5,5) = -17
         fmat(5,6) = -98
         fmat(5,7) = -36
         fmat(5,8) = 40
         fmat(5,9) = 22
         fmat(5,10) = 5
      end
