c      
c     SUBROUTINE foof4
c      
      subroutine foof4(x,y,fmat)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        doubleprecision x,y
        dimension fmat(1,2)
         fmat(1,1) = x
         fmat(1,2) = y
      end
