c      
c     SUBROUTINE foof7
c      
      subroutine foof7(k,x,ij,v,mn)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        doubleprecision k,x(2,3)
        dimension ij(3,2),v(3),mn(2)
        mn(1) = 20
        mn(2) = 20
         ij(1,1) = 15
         ij(1,2) = 6
         ij(2,1) = 2
         ij(2,2) = 4
         ij(3,1) = 1
         ij(3,2) = 1
         v(1) = k*(x(1,2)-x(2,1))
         v(2) = k*x(2,3)
         v(3) = x(1,1)+x(2,2)
      end
