function [out]=foos9(x,xxx,xxxxxxx)
// Function generated by Maple to Scilab interface
out=[
xxxxxxx*(1+8*x+28*x**2+56*x**3+70*x**4+56*x**5+28*x**6+8*x**7+x**8)+0..
.123456D3;
xxx*(1+8*x+28*x**2+56*x**3+70*x**4+56*x**5+28*x**6+8*x**7+x**8)+12345..
.0;
]

endfunction
