function [out]=foos7(k,x)
// Function generated by Maple to Scilab interface
ij=[[
15;
2;
1;
],[
6;
4;
1;
]]

v=[
k*(x(1,2)-x(2,1));
k*x(2,3);
x(1,1)+x(2,2);
]

out=sparse(ij,v,[20,20])
endfunction
