// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
libintertest_path=get_file_path('loader.sce');
functions=[ 'scifun1';
];
addinter(libintertest_path+'/libintertest.so','libintertest',functions);
