#
# Warning: this file has been generated.
#
# DO NOT EDIT THIS FILE!
#
# The editable source of this file is in Config.mk.in
#
#!/bin/sh
######################################################################
#                                                                    #
#                           ScicosLab                                #
#                                                                    #
#          Pierre Weis, INRIA Rocquencourt                           #
#                                                                    #
#  Copyright 2010-2011,                                              #
#  Institut National de Recherche en Informatique et en Automatique. #
#  All rights reserved.                                              #
#                                                                    #
#  This file is distributed under the terms of the Q Public License. #
#                                                                    #
######################################################################

# $Id: Config.mk.in 4500 2011-09-16 22:48:46Z weis $

SRC_ROOT_DIR="/usr/local/src/scicoslab-svnrepos/scicoslab-sosie"
PREFIX_INSTALL_DIR="/usr/local"
SRC_INSTALL_DIR="/usr/local/src/scicoslab-svnrepos/scicoslab-sosie"/scilab

include $(ROOT_DIR)/config/Params.mk
include $(ROOT_DIR)/config/Commands.mk
