c      
c     SUBROUTINE aa
c      
      subroutine aa(q,qd,u,param,b0,b1,a0,fmat)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        doubleprecision q(23),qd(23),u(2),param(23),b0,b1,a0
        dimension fmat(43,1)
         fmat(42,1) = -(-param(7)*(qd(23)+cos(q(15))*qd(14))*sin(q(14))-
     +cos(q(14))*sin(q(15))*qd(15)*param(7))*qd(14)-(-param(7)*sin(q(15)
     +)*qd(14)*cos(q(14))-sin(q(14))*cos(q(15))*qd(15)*param(7))*qd(15)-
     +a0*(param(7)*(qd(23)+cos(q(15))*qd(14))*cos(q(14))-sin(q(14))*sin(
     +q(15))*qd(15)*param(7)+qd(20))
         fmat(23,1) = param(5)*sin(q(15))*qd(14)*qd(15)
         fmat(15,1) = -(qd(14)*(param(11)-param(12))*cos(q(15))*sin(q(15
     +))-qd(14)*cos(q(15))*sin(q(15))*(param(11)-param(12))*cos(q(16))**
     +2+qd(14)*(param(15)-param(14))*cos(q(15))*sin(q(15))-qd(14)*cos(q(
     +15))*sin(q(15))*(param(15)-param(14))*cos(q(16))**2+param(11)*sin(
     +q(15))*qd(16)/2+param(15)*sin(q(15))*qd(16)/2+cos(q(15))*sin(q(16)
     +)*qd(15)*(param(15)-param(14))*cos(q(16))/2+cos(q(15))*sin(q(16))*
     +qd(15)*(param(11)-param(12))*cos(q(16))/2+param(5)*sin(q(15))*qd(2
     +3)/2-qd(14)*(param(4)-param(5))*cos(q(15))*sin(q(15)))*qd(14)-(-co
     +s(q(15))*sin(q(16))*qd(14)*(param(15)-param(14))*cos(q(16))/2-cos(
     +q(15))*sin(q(16))*qd(14)*(param(11)-param(12))*cos(q(16))/2)*qd(15
     +)-(2*qd(15)*(param(11)-param(12))*cos(q(16))*sin(q(16))+2*qd(15)*(
     +param(15)-param(14))*cos(q(16))*sin(q(16))-sin(q(15))*cos(q(16))**
     +2*qd(14)*(param(15)-param(14))+sin(q(15))*sin(q(16))**2*qd(14)*(pa
     +ram(15)-param(14))-sin(q(15))*cos(q(16))**2*qd(14)*(param(11)-para
     +m(12))+sin(q(15))*sin(q(16))**2*qd(14)*(param(11)-param(12))+param
     +(11)*sin(q(15))*qd(14)/2+param(15)*sin(q(15))*qd(14)/2)*qd(16)-par
     +am(5)*sin(q(15))*qd(14)*qd(23)/2
         fmat(25,1) = -b1*qd(2)-(b1*(cos(q(4))*cos(q(10))-sin(q(4))*cos(
     +q(5))*sin(q(10)))*param(18)+(-sin(q(4))*cos(q(10))-cos(q(4))*cos(q
     +(5))*sin(q(10)))*param(18)*qd(4)+sin(q(4))*sin(q(5))*sin(q(10))*pa
     +ram(18)*qd(5)+(-cos(q(4))*sin(q(10))-sin(q(4))*cos(q(5))*cos(q(10)
     +))*param(18)*qd(10))*qd(4)-(-b1*cos(q(4))*sin(q(5))*sin(q(10))*par
     +am(18)+sin(q(4))*sin(q(5))*sin(q(10))*param(18)*qd(4)-cos(q(4))*co
     +s(q(5))*sin(q(10))*param(18)*qd(5)-cos(q(4))*sin(q(5))*cos(q(10))*
     +param(18)*qd(10))*qd(5)+b1*qd(8)-(b1*(-sin(q(4))*sin(q(10))+cos(q(
     +4))*cos(q(5))*cos(q(10)))*param(18)+(-cos(q(4))*sin(q(10))-sin(q(4
     +))*cos(q(5))*cos(q(10)))*param(18)*qd(4)-cos(q(4))*sin(q(5))*cos(q
     +(10))*param(18)*qd(5)+(-sin(q(4))*cos(q(10))-cos(q(4))*cos(q(5))*s
     +in(q(10)))*param(18)*qd(10))*qd(10)-b0*(q(2)-q(8)+(sin(q(4))*cos(q
     +(10))+cos(q(4))*cos(q(5))*sin(q(10)))*param(18))
         fmat(36,1) = -b1*(1-param(20)/param(18))*qd(3)-b1*param(20)/par
     +am(18)*qd(9)+b1*param(21)/param(19)*qd(13)-b1*(-1+param(21)/param(
     +19))*qd(19)-b0*(q(3)-q(19)-param(20)/param(18)*(q(3)-q(9))-param(2
     +1)/param(19)*(q(13)-q(19)))
         fmat(32,1) = -(b1*cos(q(15))*cos(q(16))*param(22)-sin(q(15))*co
     +s(q(16))*param(22)*qd(15)-cos(q(15))*sin(q(16))*param(22)*qd(16))*
     +qd(15)-(-b1*sin(q(15))*sin(q(16))*param(22)-cos(q(15))*sin(q(16))*
     +param(22)*qd(15)-sin(q(15))*cos(q(16))*param(22)*qd(16))*qd(16)+b1
     +*qd(19)-b1*qd(22)-b0*(q(22)-q(19)+sin(q(15))*cos(q(16))*param(22))
         fmat(30,1) = -(b1*(sin(q(14))*sin(q(16))-cos(q(14))*cos(q(15))*
     +cos(q(16)))*param(22)+(sin(q(14))*cos(q(15))*cos(q(16))+cos(q(14))
     +*sin(q(16)))*param(22)*qd(14)+cos(q(14))*sin(q(15))*cos(q(16))*par
     +am(22)*qd(15)+(sin(q(14))*cos(q(16))+cos(q(14))*cos(q(15))*sin(q(1
     +6)))*param(22)*qd(16))*qd(14)-(b1*sin(q(14))*sin(q(15))*cos(q(16))
     +*param(22)+cos(q(14))*sin(q(15))*cos(q(16))*param(22)*qd(14)+sin(q
     +(14))*cos(q(15))*cos(q(16))*param(22)*qd(15)-sin(q(14))*sin(q(15))
     +*sin(q(16))*param(22)*qd(16))*qd(15)-(b1*(sin(q(14))*cos(q(15))*si
     +n(q(16))-cos(q(14))*cos(q(16)))*param(22)+(sin(q(14))*cos(q(16))+c
     +os(q(14))*cos(q(15))*sin(q(16)))*param(22)*qd(14)-sin(q(14))*sin(q
     +(15))*sin(q(16))*param(22)*qd(15)+(sin(q(14))*cos(q(15))*cos(q(16)
     +)+cos(q(14))*sin(q(16)))*param(22)*qd(16))*qd(16)+b1*qd(17)-b1*qd(
     +20)-b0*(q(20)-q(17)+(-cos(q(14))*sin(q(16))-sin(q(14))*cos(q(15))*
     +cos(q(16)))*param(22))
         fmat(17,1) = 0
         fmat(12,1) = 0
         fmat(5,1) = -(qd(4)*(param(8)-param(9))*cos(q(5))*sin(q(5))-qd(
     +4)*cos(q(5))*sin(q(5))*(param(8)-param(9))*cos(q(10))**2+param(8)*
     +sin(q(5))*qd(10)/2+cos(q(5))*sin(q(10))*qd(5)*(param(8)-param(9))*
     +cos(q(10))/2+param(2)*sin(q(5))*qd(6)/2-qd(4)*(param(1)-param(2))*
     +cos(q(5))*sin(q(5)))*qd(4)+cos(q(5))*sin(q(10))*qd(4)*(param(8)-pa
     +ram(9))*cos(q(10))*qd(5)/2-param(2)*sin(q(5))*qd(4)*qd(6)/2-(2*qd(
     +5)*(param(8)-param(9))*cos(q(10))*sin(q(10))-sin(q(5))*cos(q(10))*
     +*2*qd(4)*(param(8)-param(9))+sin(q(5))*sin(q(10))**2*qd(4)*(param(
     +8)-param(9))+param(8)*sin(q(5))*qd(4)/2)*qd(10)-u(1)*cos(q(5))*sin
     +(q(4)-q(14))/(sin(q(15))*sin(q(5))*cos(q(4)-q(14))+cos(q(15))*cos(
     +q(5)))
         fmat(6,1) = param(2)*sin(q(5))*qd(4)*qd(5)+u(2)
         fmat(28,1) = -b1*qd(12)-(-b1*(cos(q(14))*cos(q(16))-sin(q(14))*
     +cos(q(15))*sin(q(16)))*param(19)-(-sin(q(14))*cos(q(16))-cos(q(14)
     +)*cos(q(15))*sin(q(16)))*param(19)*qd(14)-sin(q(14))*sin(q(15))*si
     +n(q(16))*param(19)*qd(15)-(-cos(q(14))*sin(q(16))-sin(q(14))*cos(q
     +(15))*cos(q(16)))*param(19)*qd(16))*qd(14)-(b1*cos(q(14))*sin(q(15
     +))*sin(q(16))*param(19)-sin(q(14))*sin(q(15))*sin(q(16))*param(19)
     +*qd(14)+cos(q(14))*cos(q(15))*sin(q(16))*param(19)*qd(15)+cos(q(14
     +))*sin(q(15))*cos(q(16))*param(19)*qd(16))*qd(15)-(-b1*(-sin(q(14)
     +)*sin(q(16))+cos(q(14))*cos(q(15))*cos(q(16)))*param(19)-(-cos(q(1
     +4))*sin(q(16))-sin(q(14))*cos(q(15))*cos(q(16)))*param(19)*qd(14)+
     +cos(q(14))*sin(q(15))*cos(q(16))*param(19)*qd(15)-(-sin(q(14))*cos
     +(q(16))-cos(q(14))*cos(q(15))*sin(q(16)))*param(19)*qd(16))*qd(16)
     ++b1*qd(18)-b0*(q(12)-q(18)-(sin(q(14))*cos(q(16))+cos(q(14))*cos(q
     +(15))*sin(q(16)))*param(19))
         fmat(14,1) = -(-2*qd(14)*(param(11)-param(12))*cos(q(15))*sin(q
     +(15))+2*qd(14)*cos(q(15))*sin(q(15))*(param(11)-param(12))*cos(q(1
     +6))**2-2*qd(14)*(param(15)-param(14))*cos(q(15))*sin(q(15))+2*qd(1
     +4)*cos(q(15))*sin(q(15))*(param(15)-param(14))*cos(q(16))**2-param
     +(11)*sin(q(15))*qd(16)-param(15)*sin(q(15))*qd(16)-cos(q(15))*sin(
     +q(16))*qd(15)*(param(15)-param(14))*cos(q(16))-cos(q(15))*sin(q(16
     +))*qd(15)*(param(11)-param(12))*cos(q(16))-param(5)*sin(q(15))*qd(
     +23)+2*qd(14)*(param(4)-param(5))*cos(q(15))*sin(q(15)))*qd(15)-((2
     +*qd(14)*cos(q(15))**2-2*qd(14))*(param(11)-param(12))*cos(q(16))*s
     +in(q(16))+(2*qd(14)*cos(q(15))**2-2*qd(14))*(param(15)-param(14))*
     +cos(q(16))*sin(q(16))-sin(q(15))*cos(q(16))**2*qd(15)*(param(15)-p
     +aram(14))+sin(q(15))*sin(q(16))**2*qd(15)*(param(15)-param(14))-si
     +n(q(15))*cos(q(16))**2*qd(15)*(param(11)-param(12))+sin(q(15))*sin
     +(q(16))**2*qd(15)*(param(11)-param(12)))*qd(16)+u(1)*sin(q(5))*cos
     +(q(4)-q(14))/(sin(q(15))*sin(q(5))*cos(q(4)-q(14))+cos(q(15))*cos(
     +q(5)))
         fmat(1,1) = 0
         fmat(29,1) = -b1*qd(13)-(-b1*cos(q(15))*sin(q(16))*param(19)+si
     +n(q(15))*sin(q(16))*param(19)*qd(15)-cos(q(15))*cos(q(16))*param(1
     +9)*qd(16))*qd(15)-(-b1*sin(q(15))*cos(q(16))*param(19)-cos(q(15))*
     +cos(q(16))*param(19)*qd(15)+sin(q(15))*sin(q(16))*param(19)*qd(16)
     +)*qd(16)+b1*qd(19)-b0*(q(13)-q(19)-sin(q(15))*sin(q(16))*param(19)
     +)
         fmat(9,1) = -param(10)*param(23)
         fmat(7,1) = 0
         fmat(34,1) = -b1*(1-param(20)/param(18))*qd(1)-b1*param(20)/par
     +am(18)*qd(7)+b1*param(21)/param(19)*qd(11)-b1*(-1+param(21)/param(
     +19))*qd(17)-b0*(q(1)-q(17)-param(20)/param(18)*(q(1)-q(7))-param(2
     +1)/param(19)*(q(11)-q(17)))
         fmat(2,1) = 0
         fmat(19,1) = -param(16)*param(23)
         fmat(39,1) = -(-b1*cos(q(15))*param(7)+sin(q(15))*param(7)*qd(1
     +5))*qd(15)-b1*qd(22)-b0*(q(22)-sin(q(15))*param(7))
         fmat(21,1) = 0
         fmat(20,1) = 0
         fmat(13,1) = -param(13)*param(23)
         fmat(26,1) = -b1*qd(3)-(b1*cos(q(5))*sin(q(10))*param(18)-sin(q
     +(5))*sin(q(10))*param(18)*qd(5)+cos(q(5))*cos(q(10))*param(18)*qd(
     +10))*qd(5)+b1*qd(9)-(b1*sin(q(5))*cos(q(10))*param(18)+cos(q(5))*c
     +os(q(10))*param(18)*qd(5)-sin(q(5))*sin(q(10))*param(18)*qd(10))*q
     +d(10)-b0*(q(3)-q(9)+sin(q(5))*sin(q(10))*param(18))
         fmat(8,1) = 0
         fmat(31,1) = -(b1*(-cos(q(14))*sin(q(16))-sin(q(14))*cos(q(15))
     +*cos(q(16)))*param(22)+(sin(q(14))*sin(q(16))-cos(q(14))*cos(q(15)
     +)*cos(q(16)))*param(22)*qd(14)+sin(q(14))*sin(q(15))*cos(q(16))*pa
     +ram(22)*qd(15)+(sin(q(14))*cos(q(15))*sin(q(16))-cos(q(14))*cos(q(
     +16)))*param(22)*qd(16))*qd(14)-(-b1*cos(q(14))*sin(q(15))*cos(q(16
     +))*param(22)+sin(q(14))*sin(q(15))*cos(q(16))*param(22)*qd(14)-cos
     +(q(14))*cos(q(15))*cos(q(16))*param(22)*qd(15)+cos(q(14))*sin(q(15
     +))*sin(q(16))*param(22)*qd(16))*qd(15)-(b1*(-sin(q(14))*cos(q(16))
     +-cos(q(14))*cos(q(15))*sin(q(16)))*param(22)+(sin(q(14))*cos(q(15)
     +)*sin(q(16))-cos(q(14))*cos(q(16)))*param(22)*qd(14)+cos(q(14))*si
     +n(q(15))*sin(q(16))*param(22)*qd(15)+(sin(q(14))*sin(q(16))-cos(q(
     +14))*cos(q(15))*cos(q(16)))*param(22)*qd(16))*qd(16)+b1*qd(18)-b1*
     +qd(21)-b0*(q(21)-q(18)+(-sin(q(14))*sin(q(16))+cos(q(14))*cos(q(15
     +))*cos(q(16)))*param(22))
         fmat(37,1) = -(b1*(cos(q(4))*sin(q(5))*(cos(q(14))*cos(q(16))-s
     +in(q(14))*cos(q(15))*sin(q(16)))*param(19)+sin(q(4))*sin(q(5))*(si
     +n(q(14))*cos(q(16))+cos(q(14))*cos(q(15))*sin(q(16)))*param(19))+(
     +-sin(q(4))*sin(q(5))*(cos(q(14))*cos(q(16))-sin(q(14))*cos(q(15))*
     +sin(q(16)))*param(19)+cos(q(4))*sin(q(5))*(sin(q(14))*cos(q(16))+c
     +os(q(14))*cos(q(15))*sin(q(16)))*param(19))*qd(4)+(cos(q(4))*cos(q
     +(5))*(cos(q(14))*cos(q(16))-sin(q(14))*cos(q(15))*sin(q(16)))*para
     +m(19)+sin(q(4))*cos(q(5))*(sin(q(14))*cos(q(16))+cos(q(14))*cos(q(
     +15))*sin(q(16)))*param(19))*qd(5)+(cos(q(4))*sin(q(5))*(-sin(q(14)
     +)*cos(q(16))-cos(q(14))*cos(q(15))*sin(q(16)))*param(19)+sin(q(4))
     +*sin(q(5))*(cos(q(14))*cos(q(16))-sin(q(14))*cos(q(15))*sin(q(16))
     +)*param(19))*qd(14)+(cos(q(4))*sin(q(5))*sin(q(14))*sin(q(15))*sin
     +(q(16))*param(19)-sin(q(4))*sin(q(5))*cos(q(14))*sin(q(15))*sin(q(
     +16))*param(19))*qd(15)+(cos(q(4))*sin(q(5))*(-cos(q(14))*sin(q(16)
     +)-sin(q(14))*cos(q(15))*cos(q(16)))*param(19)+sin(q(4))*sin(q(5))*
     +(-sin(q(14))*sin(q(16))+cos(q(14))*cos(q(15))*cos(q(16)))*param(19
     +))*qd(16))*qd(4)-(b1*(sin(q(4))*cos(q(5))*(cos(q(14))*cos(q(16))-s
     +in(q(14))*cos(q(15))*sin(q(16)))*param(19)-cos(q(4))*cos(q(5))*(si
     +n(q(14))*cos(q(16))+cos(q(14))*cos(q(15))*sin(q(16)))*param(19)-si
     +n(q(5))*sin(q(15))*sin(q(16))*param(19))+(cos(q(4))*cos(q(5))*(cos
     +(q(14))*cos(q(16))-sin(q(14))*cos(q(15))*sin(q(16)))*param(19)+sin
     +(q(4))*cos(q(5))*(sin(q(14))*cos(q(16))+cos(q(14))*cos(q(15))*sin(
     +q(16)))*param(19))*qd(4)+(-sin(q(4))*sin(q(5))*(cos(q(14))*cos(q(1
     +6))-sin(q(14))*cos(q(15))*sin(q(16)))*param(19)+cos(q(4))*sin(q(5)
     +)*(sin(q(14))*cos(q(16))+cos(q(14))*cos(q(15))*sin(q(16)))*param(1
     +9)-cos(q(5))*sin(q(15))*sin(q(16))*param(19))*qd(5)+(sin(q(4))*cos
     +(q(5))*(-sin(q(14))*cos(q(16))-cos(q(14))*cos(q(15))*sin(q(16)))*p
     +aram(19)-cos(q(4))*cos(q(5))*(cos(q(14))*cos(q(16))-sin(q(14))*cos
     +(q(15))*sin(q(16)))*param(19))*qd(14)+(sin(q(4))*cos(q(5))*sin(q(1
     +4))*sin(q(15))*sin(q(16))*param(19)+cos(q(4))*cos(q(5))*cos(q(14))
     +*sin(q(15))*sin(q(16))*param(19)-sin(q(5))*cos(q(15))*sin(q(16))*p
     +aram(19))*qd(15)+(sin(q(4))*cos(q(5))*(-cos(q(14))*sin(q(16))-sin(
     +q(14))*cos(q(15))*cos(q(16)))*param(19)-cos(q(4))*cos(q(5))*(-sin(
     +q(14))*sin(q(16))+cos(q(14))*cos(q(15))*cos(q(16)))*param(19)-sin(
     +q(5))*sin(q(15))*cos(q(16))*param(19))*qd(16))*qd(5)-(b1*(sin(q(4)
     +)*sin(q(5))*(-sin(q(14))*cos(q(16))-cos(q(14))*cos(q(15))*sin(q(16
     +)))*param(19)-cos(q(4))*sin(q(5))*(cos(q(14))*cos(q(16))-sin(q(14)
     +)*cos(q(15))*sin(q(16)))*param(19))+(cos(q(4))*sin(q(5))*(-sin(q(1
     +4))*cos(q(16))-cos(q(14))*cos(q(15))*sin(q(16)))*param(19)+sin(q(4
     +))*sin(q(5))*(cos(q(14))*cos(q(16))-sin(q(14))*cos(q(15))*sin(q(16
     +)))*param(19))*qd(4)+(sin(q(4))*cos(q(5))*(-sin(q(14))*cos(q(16))-
     +cos(q(14))*cos(q(15))*sin(q(16)))*param(19)-cos(q(4))*cos(q(5))*(c
     +os(q(14))*cos(q(16))-sin(q(14))*cos(q(15))*sin(q(16)))*param(19))*
     +qd(5)+(sin(q(4))*sin(q(5))*(sin(q(14))*cos(q(15))*sin(q(16))-cos(q
     +(14))*cos(q(16)))*param(19)-cos(q(4))*sin(q(5))*(-sin(q(14))*cos(q
     +(16))-cos(q(14))*cos(q(15))*sin(q(16)))*param(19))*qd(14)+(sin(q(4
     +))*sin(q(5))*cos(q(14))*sin(q(15))*sin(q(16))*param(19)-cos(q(4))*
     +sin(q(5))*sin(q(14))*sin(q(15))*sin(q(16))*param(19))*qd(15)+(sin(
     +q(4))*sin(q(5))*(sin(q(14))*sin(q(16))-cos(q(14))*cos(q(15))*cos(q
     +(16)))*param(19)-cos(q(4))*sin(q(5))*(-cos(q(14))*sin(q(16))-sin(q
     +(14))*cos(q(15))*cos(q(16)))*param(19))*qd(16))*qd(14)-(b1*(sin(q(
     +4))*sin(q(5))*sin(q(14))*sin(q(15))*sin(q(16))*param(19)+cos(q(4))
     +*sin(q(5))*cos(q(14))*sin(q(15))*sin(q(16))*param(19)+cos(q(5))*co
     +s(q(15))*sin(q(16))*param(19))+(cos(q(4))*sin(q(5))*sin(q(14))*sin
     +(q(15))*sin(q(16))*param(19)-sin(q(4))*sin(q(5))*cos(q(14))*sin(q(
     +15))*sin(q(16))*param(19))*qd(4)+(sin(q(4))*cos(q(5))*sin(q(14))*s
     +in(q(15))*sin(q(16))*param(19)+cos(q(4))*cos(q(5))*cos(q(14))*sin(
     +q(15))*sin(q(16))*param(19)-sin(q(5))*cos(q(15))*sin(q(16))*param(
     +19))*qd(5)+(sin(q(4))*sin(q(5))*cos(q(14))*sin(q(15))*sin(q(16))*p
     +aram(19)-cos(q(4))*sin(q(5))*sin(q(14))*sin(q(15))*sin(q(16))*para
     +m(19))*qd(14)+(sin(q(4))*sin(q(5))*sin(q(14))*cos(q(15))*sin(q(16)
     +)*param(19)+cos(q(4))*sin(q(5))*cos(q(14))*cos(q(15))*sin(q(16))*p
     +aram(19)-cos(q(5))*sin(q(15))*sin(q(16))*param(19))*qd(15)+(sin(q(
     +4))*sin(q(5))*sin(q(14))*sin(q(15))*cos(q(16))*param(19)+cos(q(4))
     +*sin(q(5))*cos(q(14))*sin(q(15))*cos(q(16))*param(19)+cos(q(5))*co
     +s(q(15))*cos(q(16))*param(19))*qd(16))*qd(15)-(b1*(sin(q(4))*sin(q
     +(5))*(-cos(q(14))*sin(q(16))-sin(q(14))*cos(q(15))*cos(q(16)))*par
     +am(19)-cos(q(4))*sin(q(5))*(-sin(q(14))*sin(q(16))+cos(q(14))*cos(
     +q(15))*cos(q(16)))*param(19)+cos(q(5))*sin(q(15))*cos(q(16))*param
     +(19))+(cos(q(4))*sin(q(5))*(-cos(q(14))*sin(q(16))-sin(q(14))*cos(
     +q(15))*cos(q(16)))*param(19)+sin(q(4))*sin(q(5))*(-sin(q(14))*sin(
     +q(16))+cos(q(14))*cos(q(15))*cos(q(16)))*param(19))*qd(4)+(sin(q(4
     +))*cos(q(5))*(-cos(q(14))*sin(q(16))-sin(q(14))*cos(q(15))*cos(q(1
     +6)))*param(19)-cos(q(4))*cos(q(5))*(-sin(q(14))*sin(q(16))+cos(q(1
     +4))*cos(q(15))*cos(q(16)))*param(19)-sin(q(5))*sin(q(15))*cos(q(16
     +))*param(19))*qd(5)+(sin(q(4))*sin(q(5))*(sin(q(14))*sin(q(16))-co
     +s(q(14))*cos(q(15))*cos(q(16)))*param(19)-cos(q(4))*sin(q(5))*(-co
     +s(q(14))*sin(q(16))-sin(q(14))*cos(q(15))*cos(q(16)))*param(19))*q
     +d(14)+(sin(q(4))*sin(q(5))*sin(q(14))*sin(q(15))*cos(q(16))*param(
     +19)+cos(q(4))*sin(q(5))*cos(q(14))*sin(q(15))*cos(q(16))*param(19)
     ++cos(q(5))*cos(q(15))*cos(q(16))*param(19))*qd(15)+(sin(q(4))*sin(
     +q(5))*(sin(q(14))*cos(q(15))*sin(q(16))-cos(q(14))*cos(q(16)))*par
     +am(19)-cos(q(4))*sin(q(5))*(-sin(q(14))*cos(q(16))-cos(q(14))*cos(
     +q(15))*sin(q(16)))*param(19)-cos(q(5))*sin(q(15))*sin(q(16))*param
     +(19))*qd(16))*qd(16)-b0*(sin(q(4))*sin(q(5))*(cos(q(14))*cos(q(16)
     +)-sin(q(14))*cos(q(15))*sin(q(16)))*param(19)-cos(q(4))*sin(q(5))*
     +(sin(q(14))*cos(q(16))+cos(q(14))*cos(q(15))*sin(q(16)))*param(19)
     ++cos(q(5))*sin(q(15))*sin(q(16))*param(19))
         fmat(43,1) = -(param(7)*(qd(23)+cos(q(15))*qd(14))*cos(q(14))-s
     +in(q(14))*sin(q(15))*qd(15)*param(7))*qd(14)-(-param(7)*sin(q(15))
     +*qd(14)*sin(q(14))+cos(q(14))*cos(q(15))*qd(15)*param(7))*qd(15)-a
     +0*(param(7)*(qd(23)+cos(q(15))*qd(14))*sin(q(14))+cos(q(14))*sin(q
     +(15))*qd(15)*param(7)+qd(21))
         fmat(33,1) = -(b1*(2*q(1)-2*q(17))+2*qd(1)-2*qd(17))*qd(1)-(b1*
     +(2*q(2)-2*q(18))+2*qd(2)-2*qd(18))*qd(2)-(b1*(2*q(3)-2*q(19))+2*qd
     +(3)-2*qd(19))*qd(3)-(b1*(-2*q(1)+2*q(17))-2*qd(1)+2*qd(17))*qd(17)
     +-(b1*(-2*q(2)+2*q(18))-2*qd(2)+2*qd(18))*qd(18)-(b1*(-2*q(3)+2*q(1
     +9))-2*qd(3)+2*qd(19))*qd(19)-b0*((q(1)-q(17))**2+(q(2)-q(18))**2+(
     +q(3)-q(19))**2-param(17)**2)
         fmat(11,1) = 0
         fmat(10,1) = -(-(2*qd(4)*cos(q(5))**2-2*qd(4))*(param(8)-param(
     +9))*cos(q(10))*sin(q(10))/2+sin(q(5))*cos(q(10))**2*qd(5)*(param(8
     +)-param(9))/2-sin(q(5))*sin(q(10))**2*qd(5)*(param(8)-param(9))/2)
     +*qd(4)-(-param(8)*sin(q(5))*qd(4)-qd(5)*(param(8)-param(9))*cos(q(
     +10))*sin(q(10))+sin(q(5))*cos(q(10))**2*qd(4)*(param(8)-param(9))/
     +2-sin(q(5))*sin(q(10))**2*qd(4)*(param(8)-param(9))/2)*qd(5)
         fmat(24,1) = -b1*qd(1)-(b1*(-sin(q(4))*cos(q(10))-cos(q(4))*cos
     +(q(5))*sin(q(10)))*param(18)+(-cos(q(4))*cos(q(10))+sin(q(4))*cos(
     +q(5))*sin(q(10)))*param(18)*qd(4)+cos(q(4))*sin(q(5))*sin(q(10))*p
     +aram(18)*qd(5)+(sin(q(4))*sin(q(10))-cos(q(4))*cos(q(5))*cos(q(10)
     +))*param(18)*qd(10))*qd(4)-(b1*sin(q(4))*sin(q(5))*sin(q(10))*para
     +m(18)+cos(q(4))*sin(q(5))*sin(q(10))*param(18)*qd(4)+sin(q(4))*cos
     +(q(5))*sin(q(10))*param(18)*qd(5)+sin(q(4))*sin(q(5))*cos(q(10))*p
     +aram(18)*qd(10))*qd(5)+b1*qd(7)-(b1*(-cos(q(4))*sin(q(10))-sin(q(4
     +))*cos(q(5))*cos(q(10)))*param(18)+(sin(q(4))*sin(q(10))-cos(q(4))
     +*cos(q(5))*cos(q(10)))*param(18)*qd(4)+sin(q(4))*sin(q(5))*cos(q(1
     +0))*param(18)*qd(5)+(-cos(q(4))*cos(q(10))+sin(q(4))*cos(q(5))*sin
     +(q(10)))*param(18)*qd(10))*qd(10)-b0*(q(1)-q(7)+(cos(q(4))*cos(q(1
     +0))-sin(q(4))*cos(q(5))*sin(q(10)))*param(18))
         fmat(35,1) = -b1*(1-param(20)/param(18))*qd(2)-b1*param(20)/par
     +am(18)*qd(8)+b1*param(21)/param(19)*qd(12)-b1*(-1+param(21)/param(
     +19))*qd(18)-b0*(q(2)-q(18)-param(20)/param(18)*(q(2)-q(8))-param(2
     +1)/param(19)*(q(12)-q(18)))
         fmat(40,1) = -(-param(7)*(qd(6)+cos(q(5))*qd(4))*sin(q(4))-cos(
     +q(4))*sin(q(5))*qd(5)*param(7))*qd(4)-(-param(7)*sin(q(5))*qd(4)*c
     +os(q(4))-sin(q(4))*cos(q(5))*qd(5)*param(7))*qd(5)-a0*(param(7)*(q
     +d(6)+cos(q(5))*qd(4))*cos(q(4))-sin(q(4))*sin(q(5))*qd(5)*param(7)
     ++qd(1))
         fmat(41,1) = -(param(7)*(qd(6)+cos(q(5))*qd(4))*cos(q(4))-sin(q
     +(4))*sin(q(5))*qd(5)*param(7))*qd(4)-(-param(7)*sin(q(5))*qd(4)*si
     +n(q(4))+cos(q(4))*cos(q(5))*qd(5)*param(7))*qd(5)-a0*(param(7)*(qd
     +(6)+cos(q(5))*qd(4))*sin(q(4))+cos(q(4))*sin(q(5))*qd(5)*param(7)+
     +qd(2))
         fmat(4,1) = -(-2*qd(4)*(param(8)-param(9))*cos(q(5))*sin(q(5))+
     +2*qd(4)*cos(q(5))*sin(q(5))*(param(8)-param(9))*cos(q(10))**2-para
     +m(8)*sin(q(5))*qd(10)-cos(q(5))*sin(q(10))*qd(5)*(param(8)-param(9
     +))*cos(q(10))-param(2)*sin(q(5))*qd(6)+2*qd(4)*(param(1)-param(2))
     +*cos(q(5))*sin(q(5)))*qd(5)-((2*qd(4)*cos(q(5))**2-2*qd(4))*(param
     +(8)-param(9))*cos(q(10))*sin(q(10))-sin(q(5))*cos(q(10))**2*qd(5)*
     +(param(8)-param(9))+sin(q(5))*sin(q(10))**2*qd(5)*(param(8)-param(
     +9)))*qd(10)-u(1)*sin(q(5))*cos(q(4)-q(14))/(sin(q(15))*sin(q(5))*c
     +os(q(4)-q(14))+cos(q(15))*cos(q(5)))
         fmat(38,1) = -b1*qd(3)-(-b1*cos(q(5))*param(7)+sin(q(5))*param(
     +7)*qd(5))*qd(5)-b0*(q(3)-sin(q(5))*param(7))
         fmat(3,1) = -param(3)*param(23)
         fmat(18,1) = 0
         fmat(16,1) = -(-(2*qd(14)*cos(q(15))**2-2*qd(14))*(param(11)-pa
     +ram(12))*cos(q(16))*sin(q(16))/2-(2*qd(14)*cos(q(15))**2-2*qd(14))
     +*(param(15)-param(14))*cos(q(16))*sin(q(16))/2+sin(q(15))*cos(q(16
     +))**2*qd(15)*(param(15)-param(14))/2-sin(q(15))*sin(q(16))**2*qd(1
     +5)*(param(15)-param(14))/2+sin(q(15))*cos(q(16))**2*qd(15)*(param(
     +11)-param(12))/2-sin(q(15))*sin(q(16))**2*qd(15)*(param(11)-param(
     +12))/2)*qd(14)-(-param(11)*sin(q(15))*qd(14)-param(15)*sin(q(15))*
     +qd(14)-qd(15)*(param(11)-param(12))*cos(q(16))*sin(q(16))-qd(15)*(
     +param(15)-param(14))*cos(q(16))*sin(q(16))+sin(q(15))*cos(q(16))**
     +2*qd(14)*(param(15)-param(14))/2-sin(q(15))*sin(q(16))**2*qd(14)*(
     +param(15)-param(14))/2+sin(q(15))*cos(q(16))**2*qd(14)*(param(11)-
     +param(12))/2-sin(q(15))*sin(q(16))**2*qd(14)*(param(11)-param(12))
     +/2)*qd(15)+u(1)*cos(q(16))*sin(q(5))*sin(q(4)-q(14))/(sin(q(15))*s
     +in(q(5))*cos(q(4)-q(14))+cos(q(15))*cos(q(5)))/sin(q(16))
         fmat(22,1) = -param(6)*param(23)
         fmat(27,1) = -b1*qd(11)-(-b1*(-sin(q(14))*cos(q(16))-cos(q(14))
     +*cos(q(15))*sin(q(16)))*param(19)-(sin(q(14))*cos(q(15))*sin(q(16)
     +)-cos(q(14))*cos(q(16)))*param(19)*qd(14)-cos(q(14))*sin(q(15))*si
     +n(q(16))*param(19)*qd(15)-(sin(q(14))*sin(q(16))-cos(q(14))*cos(q(
     +15))*cos(q(16)))*param(19)*qd(16))*qd(14)-(-b1*sin(q(14))*sin(q(15
     +))*sin(q(16))*param(19)-cos(q(14))*sin(q(15))*sin(q(16))*param(19)
     +*qd(14)-sin(q(14))*cos(q(15))*sin(q(16))*param(19)*qd(15)-sin(q(14
     +))*sin(q(15))*cos(q(16))*param(19)*qd(16))*qd(15)-(-b1*(-cos(q(14)
     +)*sin(q(16))-sin(q(14))*cos(q(15))*cos(q(16)))*param(19)-(sin(q(14
     +))*sin(q(16))-cos(q(14))*cos(q(15))*cos(q(16)))*param(19)*qd(14)-s
     +in(q(14))*sin(q(15))*cos(q(16))*param(19)*qd(15)-(sin(q(14))*cos(q
     +(15))*sin(q(16))-cos(q(14))*cos(q(16)))*param(19)*qd(16))*qd(16)+b
     +1*qd(17)-b0*(q(11)-q(17)-(cos(q(14))*cos(q(16))-sin(q(14))*cos(q(1
     +5))*sin(q(16)))*param(19))
      end
