c      
c     SUBROUTINE fg
c      
      subroutine fg(q,qd,param,fmat)
c       
c       Function generated by Maple to Scilab interface
c       
        implicit doubleprecision (a-h,o-z)
        doubleprecision q(23),qd(23),param(23)
        dimension fmat(36,1)
         fmat(23,1) = (sin(q(14))*sin(q(16))-cos(q(14))*cos(q(15))*cos(q
     +(16)))*param(22)*qd(14)+sin(q(14))*sin(q(15))*cos(q(16))*param(22)
     +*qd(15)+(sin(q(14))*cos(q(15))*sin(q(16))-cos(q(14))*cos(q(16)))*p
     +aram(22)*qd(16)-qd(17)+qd(20)
         fmat(15,1) = q(3)-sin(q(5))*param(7)
         fmat(25,1) = cos(q(15))*cos(q(16))*param(22)*qd(15)-sin(q(15))*
     +sin(q(16))*param(22)*qd(16)-qd(19)+qd(22)
         fmat(36,1) = param(7)*(qd(23)+cos(q(15))*qd(14))*sin(q(14))+cos
     +(q(14))*sin(q(15))*qd(15)*param(7)+qd(21)
         fmat(32,1) = -cos(q(15))*param(7)*qd(15)+qd(22)
         fmat(30,1) = (cos(q(4))*sin(q(5))*(cos(q(14))*cos(q(16))-sin(q(
     +14))*cos(q(15))*sin(q(16)))*param(19)+sin(q(4))*sin(q(5))*(sin(q(1
     +4))*cos(q(16))+cos(q(14))*cos(q(15))*sin(q(16)))*param(19))*qd(4)+
     +(sin(q(4))*cos(q(5))*(cos(q(14))*cos(q(16))-sin(q(14))*cos(q(15))*
     +sin(q(16)))*param(19)-cos(q(4))*cos(q(5))*(sin(q(14))*cos(q(16))+c
     +os(q(14))*cos(q(15))*sin(q(16)))*param(19)-sin(q(5))*sin(q(15))*si
     +n(q(16))*param(19))*qd(5)+(sin(q(4))*sin(q(5))*(-sin(q(14))*cos(q(
     +16))-cos(q(14))*cos(q(15))*sin(q(16)))*param(19)-cos(q(4))*sin(q(5
     +))*(cos(q(14))*cos(q(16))-sin(q(14))*cos(q(15))*sin(q(16)))*param(
     +19))*qd(14)+(sin(q(4))*sin(q(5))*sin(q(14))*sin(q(15))*sin(q(16))*
     +param(19)+cos(q(4))*sin(q(5))*cos(q(14))*sin(q(15))*sin(q(16))*par
     +am(19)+cos(q(5))*cos(q(15))*sin(q(16))*param(19))*qd(15)+(sin(q(4)
     +)*sin(q(5))*(-cos(q(14))*sin(q(16))-sin(q(14))*cos(q(15))*cos(q(16
     +)))*param(19)-cos(q(4))*sin(q(5))*(-sin(q(14))*sin(q(16))+cos(q(14
     +))*cos(q(15))*cos(q(16)))*param(19)+cos(q(5))*sin(q(15))*cos(q(16)
     +)*param(19))*qd(16)
         fmat(17,1) = qd(1)+(-sin(q(4))*cos(q(10))-cos(q(4))*cos(q(5))*s
     +in(q(10)))*param(18)*qd(4)+sin(q(4))*sin(q(5))*sin(q(10))*param(18
     +)*qd(5)-qd(7)+(-cos(q(4))*sin(q(10))-sin(q(4))*cos(q(5))*cos(q(10)
     +))*param(18)*qd(10)
         fmat(12,1) = q(2)-q(18)-param(20)/param(18)*(q(2)-q(8))-param(2
     +1)/param(19)*(q(12)-q(18))
         fmat(5,1) = q(12)-q(18)-(sin(q(14))*cos(q(16))+cos(q(14))*cos(q
     +(15))*sin(q(16)))*param(19)
         fmat(6,1) = q(13)-q(19)-sin(q(15))*sin(q(16))*param(19)
         fmat(28,1) = (1-param(20)/param(18))*qd(2)+param(20)/param(18)*
     +qd(8)-param(21)/param(19)*qd(12)+(-1+param(21)/param(19))*qd(18)
         fmat(14,1) = sin(q(4))*sin(q(5))*(cos(q(14))*cos(q(16))-sin(q(1
     +4))*cos(q(15))*sin(q(16)))*param(19)-cos(q(4))*sin(q(5))*(sin(q(14
     +))*cos(q(16))+cos(q(14))*cos(q(15))*sin(q(16)))*param(19)+cos(q(5)
     +)*sin(q(15))*sin(q(16))*param(19)
         fmat(1,1) = q(1)-q(7)+(cos(q(4))*cos(q(10))-sin(q(4))*cos(q(5))
     +*sin(q(10)))*param(18)
         fmat(29,1) = (1-param(20)/param(18))*qd(3)+param(20)/param(18)*
     +qd(9)-param(21)/param(19)*qd(13)+(-1+param(21)/param(19))*qd(19)
         fmat(9,1) = q(22)-q(19)+sin(q(15))*cos(q(16))*param(22)
         fmat(7,1) = q(20)-q(17)+(-cos(q(14))*sin(q(16))-sin(q(14))*cos(
     +q(15))*cos(q(16)))*param(22)
         fmat(34,1) = param(7)*(qd(6)+cos(q(5))*qd(4))*sin(q(4))+cos(q(4
     +))*sin(q(5))*qd(5)*param(7)+qd(2)
         fmat(2,1) = q(2)-q(8)+(sin(q(4))*cos(q(10))+cos(q(4))*cos(q(5))
     +*sin(q(10)))*param(18)
         fmat(19,1) = qd(3)+cos(q(5))*sin(q(10))*param(18)*qd(5)-qd(9)+s
     +in(q(5))*cos(q(10))*param(18)*qd(10)
         fmat(21,1) = qd(12)-(cos(q(14))*cos(q(16))-sin(q(14))*cos(q(15)
     +)*sin(q(16)))*param(19)*qd(14)+cos(q(14))*sin(q(15))*sin(q(16))*pa
     +ram(19)*qd(15)-(-sin(q(14))*sin(q(16))+cos(q(14))*cos(q(15))*cos(q
     +(16)))*param(19)*qd(16)-qd(18)
         fmat(20,1) = qd(11)-(-sin(q(14))*cos(q(16))-cos(q(14))*cos(q(15
     +))*sin(q(16)))*param(19)*qd(14)-sin(q(14))*sin(q(15))*sin(q(16))*p
     +aram(19)*qd(15)-(-cos(q(14))*sin(q(16))-sin(q(14))*cos(q(15))*cos(
     +q(16)))*param(19)*qd(16)-qd(17)
         fmat(13,1) = q(3)-q(19)-param(20)/param(18)*(q(3)-q(9))-param(2
     +1)/param(19)*(q(13)-q(19))
         fmat(26,1) = (2*q(1)-2*q(17))*qd(1)+(2*q(2)-2*q(18))*qd(2)+(2*q
     +(3)-2*q(19))*qd(3)+(-2*q(1)+2*q(17))*qd(17)+(-2*q(2)+2*q(18))*qd(1
     +8)+(-2*q(3)+2*q(19))*qd(19)
         fmat(8,1) = q(21)-q(18)+(-sin(q(14))*sin(q(16))+cos(q(14))*cos(
     +q(15))*cos(q(16)))*param(22)
         fmat(31,1) = qd(3)-cos(q(5))*param(7)*qd(5)
         fmat(33,1) = param(7)*(qd(6)+cos(q(5))*qd(4))*cos(q(4))-sin(q(4
     +))*sin(q(5))*qd(5)*param(7)+qd(1)
         fmat(11,1) = q(1)-q(17)-param(20)/param(18)*(q(1)-q(7))-param(2
     +1)/param(19)*(q(11)-q(17))
         fmat(10,1) = (q(1)-q(17))**2+(q(2)-q(18))**2+(q(3)-q(19))**2-pa
     +ram(17)**2
         fmat(24,1) = (-cos(q(14))*sin(q(16))-sin(q(14))*cos(q(15))*cos(
     +q(16)))*param(22)*qd(14)-cos(q(14))*sin(q(15))*cos(q(16))*param(22
     +)*qd(15)+(-sin(q(14))*cos(q(16))-cos(q(14))*cos(q(15))*sin(q(16)))
     +*param(22)*qd(16)-qd(18)+qd(21)
         fmat(35,1) = param(7)*(qd(23)+cos(q(15))*qd(14))*cos(q(14))-sin
     +(q(14))*sin(q(15))*qd(15)*param(7)+qd(20)
         fmat(4,1) = q(11)-q(17)-(cos(q(14))*cos(q(16))-sin(q(14))*cos(q
     +(15))*sin(q(16)))*param(19)
         fmat(3,1) = q(3)-q(9)+sin(q(5))*sin(q(10))*param(18)
         fmat(18,1) = qd(2)+(cos(q(4))*cos(q(10))-sin(q(4))*cos(q(5))*si
     +n(q(10)))*param(18)*qd(4)-cos(q(4))*sin(q(5))*sin(q(10))*param(18)
     +*qd(5)-qd(8)+(-sin(q(4))*sin(q(10))+cos(q(4))*cos(q(5))*cos(q(10))
     +)*param(18)*qd(10)
         fmat(16,1) = q(22)-sin(q(15))*param(7)
         fmat(22,1) = qd(13)-cos(q(15))*sin(q(16))*param(19)*qd(15)-sin(
     +q(15))*cos(q(16))*param(19)*qd(16)-qd(19)
         fmat(27,1) = (1-param(20)/param(18))*qd(1)+param(20)/param(18)*
     +qd(7)-param(21)/param(19)*qd(11)+(-1+param(21)/param(19))*qd(17)
      end
